---
title: "Hurricane Matthew Path"
date: "October 8, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r echo=FALSE, warning=FALSE, message=FALSE}
library(dplyr)
library(leaflet)

matthewLocation <- data.frame(date = c("09-28-16", "09-29-16", "09-30-16", "10-01-16","10-02-16",
                                       "10-03-16", "10-04-16", "10-05-16", "10-06-16", "10-07-16",
                                       "10-08-16"),
                              lat = c(13.4, 13.9, 13.7, 13.3, 14.6, 16.9, 18.9, 
                                      21.1, 24.2, 27.5, 33.083),
                              lng = c(-60.7, -64, -70.8, -72.8, -74.8, -74.6, -74.3, 
                                      -74.6, -77.1, -79.6, -79.467))

ddpMap01 <- leaflet() %>% addTiles()
# ddpMap01 <- ddpMap01 %>% addMarkers(lat=33.083, lng=-79.467, popup = "McClellanville, SC")

ddpMap01 <- ddpMap01 %>% addCircleMarkers(lat = matthewLocation$lat, lng = matthewLocation$lng,
                                          radius = 5, color = "blue", weight = 4,
                                          fillColor = "red", fillOpacity = 1,
                                          popup = matthewLocation$date) %>% 
  addPolylines(lat = matthewLocation$lat, lng = matthewLocation$lng, 
               weight = 2)

ddpMap01


```

