---
title: "Stock Comparison"
author: 
date: "November 26, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r echo=FALSE, warning=FALSE, message=FALSE}
library(magrittr)
library(quantmod)
library(PerformanceAnalytics)
library(lubridate)
library(plotly)
library(tidyr)
library(dplyr)

from="2008-01-01"
to="2016-11-22"

symbols <- c("AMZN", "^DJI", "^IXIC", "^GSPC")

load("plotlyStocks.RData")

# dateCLose <- as.data.frame(index(AMZN))
# colnames(dateCLose) = "Date"
# 
# dCloseAMZN <- as.data.frame(Cl(AMZN), row.names = FALSE)
# dCloseDJI <- as.data.frame(Cl(DJI), row.names = FALSE)
# dCloseNAS <- as.data.frame(Cl(IXIC), row.names = FALSE)
# dCloseSP <- as.data.frame(Cl(GSPC), row.names = FALSE)
# 
# 
# dCLoseSymbols <- cbind(dCloseAMZN, dCloseDJI, dCloseNAS, dCloseSP)
# dCLoseSymbols <- gather(dCLoseSymbols, index, price) %>% mutate(Date = rep(dateCLose$Date,4))
# 
#   
# dailyReturnsAMZN <- as.data.frame(periodReturn(AMZN,period='daily'), row.names = FALSE)
# colnames(dailyReturnsAMZN) <- c("dReturnsAMZN")
# dailyReturnsAMZN <- mutate(dailyReturnsAMZN, cReturnAMZN = cumsum(dReturnsAMZN))
# dailyReturnsAMZN <- transmute(dailyReturnsAMZN, cReturnAMZN = cReturnAMZN)
# 
# dailyReturnsDJI <- as.data.frame(periodReturn(DJI,period='daily'), row.names = FALSE)
# colnames(dailyReturnsDJI) <- c("dReturnsDJI")
# dailyReturnsDJI <- mutate(dailyReturnsDJI, cReturnDJI = cumsum(dReturnsDJI))
# dailyReturnsDJI <- transmute(dailyReturnsDJI, cReturnDJI = cReturnDJI)
# 
# dailyReturnsNAS <- as.data.frame(periodReturn(IXIC,period='daily'), row.names = FALSE)
# colnames(dailyReturnsNAS) <- c("dReturnsNAS")
# dailyReturnsNAS <- mutate(dailyReturnsNAS, cReturnNAS = cumsum(dReturnsNAS))
# dailyReturnsNAS <- transmute(dailyReturnsNAS, cReturnNAS = cReturnNAS)
# 
# dailyReturnsSP <- as.data.frame(periodReturn(GSPC,period='daily'), row.names = FALSE)
# colnames(dailyReturnsSP) <- c("dReturnsSP")
# dailyReturnsSP <- mutate(dailyReturnsSP, cReturnSP = cumsum(dReturnsSP))
# dailyReturnsSP <- transmute(dailyReturnsSP, cReturnSP = cReturnSP)
# 
# dReturnsSymbols <- cbind(dailyReturnsAMZN, dailyReturnsDJI, dailyReturnsNAS, dailyReturnsSP)
# dReturnsSymbols <- gather(dReturnsSymbols, index, price) %>% mutate(Date = rep(dateCLose$Date,4))



# pltPrice <- plot_ly(dCLoseSymbols, x = ~Date, y = ~price)
# add_lines(pltPrice, color = ~index)

pltReturns <- plot_ly(dReturnsSymbols, x = ~Date, y = ~price)
add_lines(pltReturns, color = ~index)

```
